name: Add Issues to Backlog Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to Backlog project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Backlog project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/numbersprotocol/projects/8
          # OR for repository projects:
          # project-url: https://github.com/users/YOUR_USERNAME/projects/YOUR_PROJECT_NUMBER
          # OR for user projects:
          # project-url: https://github.com/users/YOUR_USERNAME/projects/YOUR_PROJECT_NUMBER
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}